### PR TITLE
arm64 docker support + github action

### PR DESCRIPTION
**Pull request by Just5KY**
* Added Arm64 support
* GitHub actions: 
  * Build 
  * Push

### CODE REVIEW

**Comment by tryffel** [comment]
Thank you for this! I'm new to Github actions, so we'll see how this goes.. I'll be away from my computer for some time now, so it'll take a little while for me to react better. Would you mind adding build for amd64 builds as well? And I plan to have automated tests eventually, so how would I go and add them to Github actions?

**Comment by Just5KY** [comment]
Yes, there are ways to test build using GitHub actions also docker container security testing using Synk and various other providers

https://github.com/tryffel/virtualpaper/actions/new?category=none&query=docker

**Comment by Just5KY** [comment]
Right now you will have to start the action automatically, but it  can also be set to build automatically as soon as there is a commit 

```yml
on:
  push:
    branches:
      - main
      - 'releases/**'
  ```

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

**Comment by Just5KY** [comment]
Took 1 hour to complete.
https://hub.docker.com/r/justsky/virtualpaper/tags

If I am understanding build cache correctly, that time can be reduced significantly! 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by tryffel** [comment]
Hi, I finally had a look at this and all seems well. I went to see your repository and tried to inspect the build that it contains but unfortunately all build info is already gone. Would you mind re-running the build in your own repository so that I can check the output before merging this? Thank you!

**Comment by Just5KY** [comment]
@tryffel 
here you go
https://github.com/Just5KY/virtualpaper/actions/runs/3453475839/jobs/5764098977

**Comment by tryffel** [comment]
Thank you! Do you also publish the image to Docker hub? Is it available for trying it out?

**Comment by Just5KY** [comment]
Yup
`justsky: virtualpaper`

**Comment by tryffel** [comment]
Hey, since there have been other needs for CI besides building itself, I've spent a couple of nights trying to get the builds, tests and releases to work with Drone.io, since it's the tool I'm personally more accustomed to.
The work is in the drone branch and I'm still trying to get the builds complete + unit & integrations tests to work correctly. The arm64 build will be easy to integrate into the drone build. So, I'm going to try to get the drone builds work first and then I could integrate the arm64 build into it. Your Dockerfile seems fine so it could be used as is. However, the Github action would not be needed in that case, unfortunately.  Feel free to help with the drone build, if you want to! Let's keep the pull request open for as long the CI done is completed. Thank you again!

**Comment by Just5KY** [comment]
I have never used DroneCI, but did a little searching and found this post.
https://oscarchou.com/posts/howto/droneci-multiarch-image-for-private-registry/

**Comment by tryffel** [comment]
Hello and once again thank you for your work. Although I manged to get the tests to successfully run on Drone.io, I was unable to build the docker images with it. So I've decided to use the Github Actions for building the images for now. I will migrate the tests to use Github Actions at some point as well. I'm going to make some minor changes to your proposed solution, but I will accept the PR as is and then modify the setup afterwards. Again, thank you for your contribution and sorry for having to wait so long..

**Pull request merged**
